# Final Transformation and Trying Out Multiple Models

In [24]:
# import libraries

import os
import sys
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression, ridge_regression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

In [6]:
# ------- HANDLING DIRECTORY ------- 
# root folder directory
root_folder = Path.cwd().parent

# Adding parent path to system memory
if str(root_folder) not in sys.path:
    sys.path.insert(0, str(root_folder))

# dataset folder
data_dir = root_folder / "data"

# train data directory
train_dir = data_dir / "train.csv"

# test data directory
test_dir = data_dir / "test.csv"

test_dir

WindowsPath('c:/Users/user/Desktop/housing_prediction_DF_proj_1/data/test.csv')

In [7]:
# import Required functions from script

from scripts.preprocess import transform_data, build_full_pipeline, load_and_transform

## Testing Transform Function

In [8]:
# ----- IMPORT DATASET ------
# Import train data
df_train = pd.read_csv(train_dir)

# import test data
df_test = pd.read_csv(test_dir)

df_train.head()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",22.592200,88.484911,60.5

In [9]:
df_train.columns

Index(['POSTED_BY', 'UNDER_CONSTRUCTION', 'RERA', 'BHK_NO.', 'BHK_OR_RK',
       'SQUARE_FT', 'READY_TO_MOVE', 'RESALE', 'ADDRESS', 'LONGITUDE',
       'LATITUDE', 'TARGET(PRICE_IN_LACS)'],
      dtype='object')

In [10]:
# ----- TRANSFORM DATA ------
# transform train data
X_train = transform_data(df_train)

# transform test data
X_test = transform_data(df_test)

X_test.head()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_OR_RK,RESALE,CITY,BHK_NO._CAPPED,LATITUDE_CLIPPED,LONGITUDE_CLIPPED,SQFT_PER_BHK_LOG
0,Owner,0,0,BHK,1,Surat,1,73.047700,21.262000,6.302933
1,Dealer,1,1,BHK,0,Lalitpur,2,73.148278,18.966114,5.993961
2,Dealer,0,0,BHK,1,Kolkata,2,84.304657,22.592200,6.445003
3,Dealer,0,0,BHK,1,Jaipur,3,75.584600,26.988300,6.147991
4,Owner,0,0,BHK,1,Nadiad,1,72.870000,22.700000,6.067216

In [11]:
# ----- TARGET VECTOR SPLITTING -----
# train target separation
y_train = X_train.pop("TARGET(PRICE_IN_LACS)_LOG")

# test target separation if exists
if "TARGET(PRICE_IN_LACS)_LOG" in X_test.columns:
    y_test = X_test.pop("TARGET(PRICE_IN_LACS)_LOG")
else:
    y_test = None
    print("None, Test Dataset has no target feature available")


y_train

None, Test Dataset has no target feature available

0        4.025352
1        3.951244
2        3.784190
3        4.151040
4        4.119037
           ...
29446    3.828641
29447    2.833213
29448    3.335770
29449    4.219508
29450    3.360375
Name: TARGET(PRICE_IN_LACS)_LOG, Length: 29451, dtype: float64

## LOAD AND TRANSFORM PIPELINE

In [ ]:
# ------- LOAD AND TRANSFORM PIPELINE ------
def load_and_transform (filepath):
    """
    About:
        Load and transform datasets before building full model pipeline
    input: (str)
        filepath to the data directory
    return: (pd.DataFrame, pd.Series)
        X_train, X_val, y_train, y_val
    """

    # ----- IMPORT DATASET ------
    # Import train data
    df = pd.read_csv(filepath)

    # ----- TRANSFORM DATA ------
    # transform train data
    X = transform_data(df)

    # test target separation if exists
    if "TARGET(PRICE_IN_LACS)_LOG" in X.columns:
        y = X.pop("TARGET(PRICE_IN_LACS)_LOG")
    else:
        y = None
        print("None, Test Dataset has no target feature available")

    # ----- TRAIN-VALIDATION SET SPLIT ------
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

    return X_train, X_val, y_train, y_val

## Testing Load and Transform Pipeline

In [13]:
load_and_transform?

Signature: load_and_transform(filepath)
Docstring:
About:
    Load and transform datasets before building full model pipeline
input: (str)
    filepath to the data directory
return: (pd.DataFrame, pd.Series)
    X, y
File:      c:\users\user\appdata\local\temp\ipykernel_20396\2216893356.py
Type:      function

In [14]:
# ------ LOAD AND TRANSFORM ------
# Training dataset
X_train, y_train = load_and_transform(train_dir)

# Testing dataset
X_test, y_test = load_and_transform(test_dir)

# Checking shapes
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {X_test.shape}") #But Has been assigned as None

None, Test Dataset has no target feature available
X_train shape: (29451, 10)
y_train shape: (29451,)
X_test shape: (68720, 10)
y_test shape: (68720, 10)

In [15]:
X_train.head()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_OR_RK,RESALE,CITY,BHK_NO._CAPPED,LATITUDE_CLIPPED,LONGITUDE_CLIPPED,SQFT_PER_BHK_LOG
0,Owner,0,0,BHK,1,Bangalore,2,77.597960,12.969910,6.478691
1,Dealer,0,0,BHK,1,Mysore,2,76.644605,12.274538,6.459122
2,Owner,0,0,BHK,1,Bangalore,2,77.632191,12.778033,6.147570
3,Owner,0,1,BHK,1,Ghaziabad,2,77.344500,28.642300,6.144101
4,Dealer,1,0,BHK,1,Kolkata,2,83.874699,22.592200,6.215617

In [16]:
y_train.head()

0    4.025352
1    3.951244
2    3.784190
3    4.151040
4    4.119037
Name: TARGET(PRICE_IN_LACS)_LOG, dtype: float64

In [17]:
X_test.head()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_OR_RK,RESALE,CITY,BHK_NO._CAPPED,LATITUDE_CLIPPED,LONGITUDE_CLIPPED,SQFT_PER_BHK_LOG
0,Owner,0,0,BHK,1,Surat,1,73.047700,21.262000,6.302933
1,Dealer,1,1,BHK,0,Lalitpur,2,73.148278,18.966114,5.993961
2,Dealer,0,0,BHK,1,Kolkata,2,84.304657,22.592200,6.445003
3,Dealer,0,0,BHK,1,Jaipur,3,75.584600,26.988300,6.147991
4,Owner,0,0,BHK,1,Nadiad,1,72.870000,22.700000,6.067216

In [18]:
y_test

## FULL MODEL PIPELINE

In [19]:
# ------ LOAD AND TRANSFORM DATA -------
# transform train set
X_train, y_train = load_and_transform(train_dir)    

# transform test set
X_test, y_test = load_and_transform(test_dir)

None, Test Dataset has no target feature available

In [20]:
# ----- INSTANTIATE MODELS ------

# linear Regression
lr_model = LinearRegression()

# decision tree
tree_model = DecisionTreeRegressor()

# random_forest model
rf_model = RandomForestRegressor()

# support vector regressor
svr_model = SVR()

In [21]:
build_full_pipeline?

Signature: build_full_pipeline(model_instance)
Docstring:
About:
    Builds full End-to-End ML pipeline including preprocessing (ColumnTransformation) and the model
Input:
    Model_instance (instantiated models eg. LinearRegression)
Output:
    Full Pipeline (sklearn.pipeline.Pipeline)
File:      c:\users\user\desktop\housing_prediction_df_proj_1\scripts\preprocess.py
Type:      function

In [22]:
# ------ FULL MODEL PIPELINE -----
# Pipeline with only linear Regression
pipeline = build_full_pipeline(
    model_instance=lr_model
)

pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('tge',
                                                  TargetEncoder(cols=['CITY'],
                                                                smoothing=0.1),
                                                  ['CITY']),
                                                 ('num', StandardScaler(),
                                                  ['UNDER_CONSTRUCTION', 'RERA',
                                                   'RESALE', 'BHK_NO._CAPPED',
                                                   'LATITUDE_CLIPPED',
                                                   'LONGITUDE_CLIPPED',
                                                   'SQFT_PER_BHK_LOG']),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['POSTED_BY', 'BHK_OR_RK'])],
                                   verbose_feature_names_out=False)),
                ('model', LinearRegression())])

In [23]:
# ----- TRAINING AND EVALUATE ------
# Training the linear model
pipeline.fit(X_train, y_train)

# prediction
y_pred = pipeline.predict(X_train)

# Evaluation with RMSE
np.sqrt(mean_squared_error(y_train, y_pred))

np.float64(0.5227656086412695)